apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexterm-pvc
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.resources.requests.storage }}
  storageClassName: {{ .Values.persistence.storageClass | default "local" }}
