apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexterm.fullname" . }}
  labels:
    {{- include "nexterm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nexterm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexterm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6989
          volumeMounts:
            - name: nexterm-storage
              mountPath: /app/data
      volumes:
        - name: nexterm-storage
          persistentVolumeClaim:
            claimName: nexterm-pvc
