apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexterm.fullname" . }}-pvc
  label: {{- include "nexterm.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.resources.requests.storage }}
  storageClassName: {{ .Values.persistence.storageClass | default "local" }}
