apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nexterm
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6989
  selector:
    app: nexterm
