replicaCount: 1

image:
  repository: germannewsmaker/nexterm
  tag: 1.0.1-OPEN-PREVIEW
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6989

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
