nameOverride: ""
fullnameOverride: ""

replicaCount: 1
autoscaling:
  enabled: false
image:
  repository: germannewsmaker/nexterm
  tag: 1.0.1-OPEN-PREVIEW
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6989

persistence:
  enabled: true
  storageClass: "local"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

ingress:
  enabled: true
  ingressClassName: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    # Your URL
    - host: ""
      paths:
        - /
  tls:
    - hosts:
      # Your URL
      - ""
      secretName: termchart--tls
