nameOverride: ""
fullnameOverride: ""

replicaCount: 1
autoscaling:
  enabled: false
image:
  repository: germannewsmaker/nexterm
  tag: 1.0.1-OPEN-PREVIEW
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6989

persistence:
  enabled: true
  storageClass: "local"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

ingress:
  enabled: true
  name: ""
  ingressClassName: ""
  nginx:
    enabled: false
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: term.s1.vutn.net
      paths:
        - /
  tls:
    - hosts:
      - term.s1.vutn.net
      secretName: termchart--tls
